BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "User" (
	"user_id"	INTEGER UNIQUE,
	"name"	TEXT,
	"programType"	TEXT,
	PRIMARY KEY("user_id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Events" (
	"Event_ID"	INTEGER UNIQUE,
	"Title"	TEXT,
	"Location"	TEXT,
	"ParticipantType"	TEXT,
	"EventDate"	TEXT,
	"StartTime"	TEXT,
	"EndTime"	TEXT,
	PRIMARY KEY("Event_ID" AUTOINCREMENT)
);
INSERT INTO "Events" VALUES (2282,'Check-in Empower team','Boyan Slat (tribune)','PULSERS only','MONDAY May 16','08:45am','09:15am');
INSERT INTO "Events" VALUES (2283,'Prep time Empower team','Boyan Slat (tribune)','PULSERS only','MONDAY May 16','09:00am','09:15am');
INSERT INTO "Events" VALUES (2284,'Check-in by Tom, Elkie','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 16','09:30am','10:00am');
INSERT INTO "Events" VALUES (2285,'PPI talentclass by Tom (challenge 3&4)','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 16','10:00am','11:30am');
INSERT INTO "Events" VALUES (2286,'Challenge 5stand up by Elkie','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 16','11:30am','12:30pm');
INSERT INTO "Events" VALUES (2287,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 16','12:30pm','01:00pm');
INSERT INTO "Events" VALUES (2288,'Challenge 1 lasercutting by Mathijs, challenge 2 illustrator by Davey, challenge 3-6 tutoring @ work by Zeynep','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 16','01:00pm','03:00pm');
INSERT INTO "Events" VALUES (2289,'Tutoring @ work Davey and Mathijs','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 16','03:00pm','03:30pm');
INSERT INTO "Events" VALUES (2290,'Check-out by Davey','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 16','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2291,'PPI talentclass by Tom (challenge 3&4)','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 16','10:00am','11:30am');
INSERT INTO "Events" VALUES (2292,'Challenge 1 stand up by Tom, 2 stand up by Davey, challenge 3 stand up by Susanne, challenge 4 stand op bij Mathijs, challenge 6 stand up by Zeynep','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 16','11:30am','12:30pm');
INSERT INTO "Events" VALUES (2293,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 16','12:30pm','01:00pm');
INSERT INTO "Events" VALUES (2294,'Challenge 1 lasercutting by Mathijs, challenge 2 illustrator by Davey, challenge 3-6 tutoring @ work by Zeynep','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 16','01:00pm','03:00pm');
INSERT INTO "Events" VALUES (2295,'Tutoring @ work Davey and Mathijs','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 16','03:00pm','03:30pm');
INSERT INTO "Events" VALUES (2296,'Check-out by Davey','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 16','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2297,'PPI talentclass by Elkie (challenge 1&2)','John Kormeling (prototyping space)','EMPOWERAll students','MONDAY May 16','10:00am','11:30am');
INSERT INTO "Events" VALUES (2298,'Personal Purpose Track','Boyan Slat (tribune)','EMBRACEAll students','TUESDAY May 17','09:30am','04:00pm');
INSERT INTO "Events" VALUES (2299,'Business track','John Kormeling (prototyping space)','EMBRACEAll students','TUESDAY May 17','09:30am','04:00pm');
INSERT INTO "Events" VALUES (2300,'Business track','Greta Thunberg (meeting space)','EMBRACEAll students','TUESDAY May 17','09:30am','04:00pm');
INSERT INTO "Events" VALUES (2301,'MDTE stand-up lunch','Leonardo da Vinci (experience room)','PULSERS only','TUESDAY May 17','12:00pm','01:00pm');
INSERT INTO "Events" VALUES (2302,'Board of Examiners','Leonardo da Vinci (experience room)','PULSERS only','TUESDAY May 17','04:00pm','05:00pm');
INSERT INTO "Events" VALUES (2303,'PPI thema by Thom and Doortje','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY May 18','09:30am','12:45pm');
INSERT INTO "Events" VALUES (2304,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY May 18','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2305,'Tutoring @work Davey and Mathijs','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY May 18','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2306,'Check-out by Davey','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY May 18','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2307,'Check-in Empower + Embrace team','Koybe Bryant (black tables)','PULSERS only','WEDNESDAY May 18','08:45am','09:15am');
INSERT INTO "Events" VALUES (2308,'Prep time Empower + Embrace team','Koybe Bryant (black tables)','PULSERS only','WEDNESDAY May 18','09:00am','09:15am');
INSERT INTO "Events" VALUES (2309,'Coachgroup 1 by Tom, coachgroup 3 by Erik','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY May 18','09:30am','12:45pm');
INSERT INTO "Events" VALUES (2310,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY May 18','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2311,'Tutoring @work Davey and Mathijs','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY May 18','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2312,'Check-out by Davey','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY May 18','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2313,'Group check-in (Heerenveen)','John Kormeling (prototyping space)','EMBRACEAll students','WEDNESDAY May 18','09:30am','10:00am');
INSERT INTO "Events" VALUES (2314,'Pulsed for Good day for ALL Embrace TEC students:Improve and test the prototypesWith Gert, Zeynep, Lolly, Jop & Steffie','John Kormeling (prototyping space)','EMBRACEAll students','WEDNESDAY May 18','10:00am','01:00pm');
INSERT INTO "Events" VALUES (2315,'DBWednesday timeslot: design-based working support by Zeynep and/or Steffie','John Kormeling (prototyping space)','EMBRACEAll students','WEDNESDAY May 18','01:00pm','02:30pm');
INSERT INTO "Events" VALUES (2316,'Pulsed for Good day for ALL Embrace TEC students: Improve and test the prototypesWith Gert, Zeynep, Lolly, Stella, Jop & Steffie','John Kormeling (prototyping space)','EMBRACEAll students','WEDNESDAY May 18','02:30pm','04:15pm');
INSERT INTO "Events" VALUES (2317,'Coachgroup 2 by Susanne','Leonardo da Vinci (experience room)','EMPOWERAll students','WEDNESDAY May 18','09:30am','11:30am');
INSERT INTO "Events" VALUES (2318,'EDEX @Gilde by Niels and Gert?','External','PULSERS only','WEDNESDAY May 18','08:30am','12:00pm');
INSERT INTO "Events" VALUES (2319,'Fieldtrip BRUNS by Susanne','External','EMPOWERFieldtrip','WEDNESDAY May 18','12:00pm','05:15pm');
INSERT INTO "Events" VALUES (2320,'Group coaching -> Uniqueness Story Session 4 out of 4','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY May 19','09:00am','11:00am');
INSERT INTO "Events" VALUES (2321,'Group check-in','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY May 19','11:00am','11:30am');
INSERT INTO "Events" VALUES (2322,'Pulsed for Good day for ALL Embrace TEC students: Improve and test the prototypesWith Zeynep, Steffie, Gert, Lolly & Jop','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY May 19','11:30am','01:00pm');
INSERT INTO "Events" VALUES (2323,'Tech Thursday timeslot: tech sessions and/or support by Stella, Jop or ...','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY May 19','01:00pm','02:30pm');
INSERT INTO "Events" VALUES (2324,'Pulsed for Good day for ALL Embrace TEC students: Improve and test the prototypes With Zeynep, Steffie, Gert, Lolly & Jop','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY May 19','02:30pm','03:30pm');
INSERT INTO "Events" VALUES (2325,'Check-out','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY May 19','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2326,'Group coaching -> Uniqueness Story Session 4 out of 4','John Kormeling (prototyping space)','EMBRACEAll students','THURSDAY May 19','09:00am','11:00am');
INSERT INTO "Events" VALUES (2327,'Workshop: elevate your prototype for UX by Maud','John Kormeling (prototyping space)','EMBRACEAll students','THURSDAY May 19','01:00pm','02:30pm');
INSERT INTO "Events" VALUES (2328,'Group coaching -> Uniqueness Story Session 4 out of 4','Greta Thunberg (meeting space)','EMBRACEAll students','THURSDAY May 19','09:00am','11:00am');
INSERT INTO "Events" VALUES (2329,'Workshop: video editing by Davey','Greta Thunberg (meeting space)','EMBRACEAll students','THURSDAY May 19','01:00pm','02:30pm');
INSERT INTO "Events" VALUES (2330,'Group coaching -> Uniqueness Story Session 4 out of 4','Pulsers(long table)','EMBRACEAll students','THURSDAY May 19','09:00am','11:00am');
INSERT INTO "Events" VALUES (2331,'Embrace TEC team meeting > Complete team','Pulsers(long table)','PULSERS only','THURSDAY May 19','04:00pm','05:00pm');
INSERT INTO "Events" VALUES (2332,'Group coaching -> Uniqueness Story Session 4 out of 4','Leonardo da Vinci (experience room)','EMBRACEAll students','THURSDAY May 19','09:00am','11:00am');
INSERT INTO "Events" VALUES (2333,'Workshop: social media content creation by Marianna and Zeynep','Leonardo da Vinci (experience room)','EMBRACEAll students','THURSDAY May 19','01:00pm','02:30pm');
INSERT INTO "Events" VALUES (2334,'EDEX @Gilde by Niels and Gert?','External','PULSERS only','THURSDAY May 19','08:30am','07:16pm');
INSERT INTO "Events" VALUES (2335,'Check-in Empower team','Boyan Slat (tribune)','PULSERS only','FRIDAY May 20','08:45am','09:15am');
INSERT INTO "Events" VALUES (2336,'Prep time Empower  team','Boyan Slat (tribune)','PULSERS only','FRIDAY May 20','09:00am','09:15am');
INSERT INTO "Events" VALUES (2337,'PPI thema group B by Tom','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY May 20','09:30am','12:30pm');
INSERT INTO "Events" VALUES (2338,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY May 20','12:30pm','01:00pm');
INSERT INTO "Events" VALUES (2339,'Tutoring @ work by Thom (challenge 1, 2, 5, 6), Premiere, videografie 2 by Davey (challenge2), photoshop, fotografie 2 by Mathijs (challenge 4)','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY May 20','01:00pm','03:30pm');
INSERT INTO "Events" VALUES (2340,'Check-out by Davey','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY May 20','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2341,'Coachgroup 5 by Thom','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY May 20','09:30am','12:30pm');
INSERT INTO "Events" VALUES (2342,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY May 20','12:30pm','01:00pm');
INSERT INTO "Events" VALUES (2343,'Tutoring @ work by Thom (challenge 1, 2, 5, 6), Premiere, videografie 2 by Davey (challenge2), photoshop, fotografie 2 by Mathijs (challenge 4)','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY May 20','01:00pm','03:30pm');
INSERT INTO "Events" VALUES (2344,'Check-out by Davey','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY May 20','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2345,'Coachgroup 6 by Gert','John Kormeling (prototyping space)','EMPOWERAll students','FRIDAY May 20','09:30am','12:30pm');
INSERT INTO "Events" VALUES (2346,'Coachgroep 7 by Doortje','Greta Thunberg (meeting space)','EMPOWERAll students','FRIDAY May 20','09:30am','12:15pm');
INSERT INTO "Events" VALUES (2347,'Show&Grow','Greta Thunberg (meeting space)','PULSERS only','FRIDAY May 20','12:15pm','01:15pm');
INSERT INTO "Events" VALUES (2348,'Coachgroup 4 by Elkie','Leonardo da Vinci (experience room)','EMPOWERAll students','FRIDAY May 20','09:30am','12:30pm');
INSERT INTO "Events" VALUES (2349,'Studiekeuzelessen R5 105','External','EMPOWER Challenge group 1, 3 and 5','FRIDAY May 20','09:30am','10:30am');
INSERT INTO "Events" VALUES (2350,'Studiekeuzelessen R5 105','External','EMPOWER Challenge group 1, 3 and 5','FRIDAY May 20','11:00am','12:00pm');
INSERT INTO "Events" VALUES (2351,'Studiekeuzelessen R5 105','External','EMPOWER Challenge group 1, 3 and 5','FRIDAY May 20','01:00pm','02:00pm');
INSERT INTO "Events" VALUES (2352,'Check-in Empower team','Boyan Slat (tribune)','PULSERS only','MONDAY May 23','08:45am','09:15am');
INSERT INTO "Events" VALUES (2353,'Prep time Empower team','Boyan Slat (tribune)','PULSERS only','MONDAY May 23','09:15am','09:45am');
INSERT INTO "Events" VALUES (2354,'Check-in by Tom, Elkie, Susanne,','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 23','09:45am','10:15am');
INSERT INTO "Events" VALUES (2355,'PPIby Tom, Elkie and Susanne','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 23','10:15am','11:45am');
INSERT INTO "Events" VALUES (2356,'Challenge 1stand up by Erik','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 23','11:45am','12:30pm');
INSERT INTO "Events" VALUES (2357,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 23','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2358,'@work powered by TI & DBWby Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 23','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2359,'Check-out by Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 23','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2360,'Check-in by Tom, Elkie, Susanne,','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 23','09:45am','10:15am');
INSERT INTO "Events" VALUES (2361,'PPiby Tom, Elkie and Susanne,','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 23','10:15am','11:45am');
INSERT INTO "Events" VALUES (2362,'Challenge 2 stand up bu Tom, challenge 3 stand up by Davey, challenge 4 stand op bij Mathijs, challenge 5 stand up by Elkie, challenge 6 stand up by Susanne','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 23','11:45am','12:30pm');
INSERT INTO "Events" VALUES (2363,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 23','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2364,'@work powered by TI & DBWby Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 23','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2365,'Check-out by Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 23','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2366,'Evaluation challenge 1 by Sandra','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY May 23','09:00am','09:30am');
INSERT INTO "Events" VALUES (2367,'Work on study trip idea','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY May 23','09:30am','11:30am');
INSERT INTO "Events" VALUES (2368,'Pitch study trip','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY May 23','11:30am','12:00pm');
INSERT INTO "Events" VALUES (2369,'Sport > more details will follow','External','MASTER DTEAll students','MONDAY May 23','01:00pm','04:00pm');
INSERT INTO "Events" VALUES (2370,'Track day 9> Personal Purpose by Lorna, Lolly and Sam. > Company Adventure by Peter and Stella. > Entrepreneur & Business by Jochem and Jeroen.','Boyan Slat (tribune)','EMBRACEAll students','TUESDAY May 24','09:30am','04:00pm');
INSERT INTO "Events" VALUES (2371,'Wicked challenge by Polar student team','Greta Thunberg (meeting space)','MASTER DTEAll students','TUESDAY May 24','09:00am','10:30am');
INSERT INTO "Events" VALUES (2372,'Lecture by Jo-an Kamp (lector Moral Design Strategy)','Greta Thunberg (meeting space)','MASTER DTEAll students','TUESDAY May 24','10:30am','12:00pm');
INSERT INTO "Events" VALUES (2373,'Polar challenge working time','Greta Thunberg (meeting space)','MASTER DTEAll students','TUESDAY May 24','01:00pm','04:00pm');
INSERT INTO "Events" VALUES (2374,'MDTE stand-up lunch','Leonardo da Vinci (experience room)','PULSERS only','TUESDAY May 24','12:00pm','01:00pm');
INSERT INTO "Events" VALUES (2375,'Check-inby Tom and Susanne','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY May 25','09:45am','10:15am');
INSERT INTO "Events" VALUES (2376,'Professional identityby Tom and Susanne','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY May 25','10:15am','11:45am');
INSERT INTO "Events" VALUES (2377,'@work','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY May 25','11:45am','12:15pm');
INSERT INTO "Events" VALUES (2378,'Digital dummy time','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY May 25','12:15pm','12:45pm');
INSERT INTO "Events" VALUES (2379,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY May 25','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2380,'@work powered by DBWby Davey and Jop','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY May 25','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2381,'Check-out by Davey and Jop','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY May 25','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2382,'Check-in Empower + Embrace team','Koybe Bryant (black tables)','PULSERS only','WEDNESDAY May 25','08:45am','09:15am');
INSERT INTO "Events" VALUES (2383,'Prep time Empower + Embrace team','Koybe Bryant (black tables)','PULSERS only','WEDNESDAY May 25','09:15am','09:45am');
INSERT INTO "Events" VALUES (2384,'Check-inby Tom and Susanne','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY May 25','09:45am','10:15am');
INSERT INTO "Events" VALUES (2385,'Professional identityby Tom and Susanne','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY May 25','10:15am','11:45am');
INSERT INTO "Events" VALUES (2386,'@work','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY May 25','11:45am','12:15pm');
INSERT INTO "Events" VALUES (2387,'Digital dummy time','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY May 25','12:15pm','12:45pm');
INSERT INTO "Events" VALUES (2388,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY May 25','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2389,'@work powered by DBWby Davey and Jop','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY May 25','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2390,'Check-out by Davey and Jop','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY May 25','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2391,'Group check-in -  Introducing Themes of Life','John Kormeling (prototyping space)','EMBRACEAll students','WEDNESDAY May 25','09:30am','10:00am');
INSERT INTO "Events" VALUES (2392,'Pulsed for Good day for ALL Embrace TEC students:Improve and test the prototypesWith Gert, Zeynep, Lolly, Jop & Steffie','John Kormeling (prototyping space)','EMBRACEAll students','WEDNESDAY May 25','10:00am','01:00pm');
INSERT INTO "Events" VALUES (2393,'DBWednesday timeslot: design-based working support by Zeynep, Lise and/or Steffie','John Kormeling (prototyping space)','EMBRACEAll students','WEDNESDAY May 25','01:00pm','02:30pm');
INSERT INTO "Events" VALUES (2394,'Pulsed for Good day for ALL Embrace TEC students: Improve and test the prototypesWith Gert, Zeynep, Lolly, Jop, Stella & Steffie','John Kormeling (prototyping space)','EMBRACEAll students','WEDNESDAY May 25','02:30pm','04:15pm');
INSERT INTO "Events" VALUES (2395,'Polar challenge working time','External >>  TU/e innovations space (Kranenveld 12)','MASTER DTEAll students','WEDNESDAY May 25','09:00am','03:30pm');
INSERT INTO "Events" VALUES (2396,'Presentation solutions Polar challenge','External >>  TU/e innovations space (Kranenveld 12)','MASTER DTEAll students','WEDNESDAY May 25','03:30pm','05:00pm');
INSERT INTO "Events" VALUES (2397,'Ascension day','Boyan Slat (tribune)',NULL,'THURSDAY May 26','08:30am','07:16pm');
INSERT INTO "Events" VALUES (2398,'Free day','Boyan Slat (tribune)',NULL,'FRIDAY May 27','08:30am','07:16pm');
INSERT INTO "Events" VALUES (2399,'Check-in Empower team','Boyan Slat (tribune)','PULSERS only','MONDAY May 30','08:45am','09:15am');
INSERT INTO "Events" VALUES (2400,'Prep time Empower team','Boyan Slat (tribune)','PULSERS only','MONDAY May 30','09:15am','09:45am');
INSERT INTO "Events" VALUES (2401,'Check-in by Tom, Elkie, Susanne,','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 30','09:45am','10:15am');
INSERT INTO "Events" VALUES (2402,'PPIby Tom, Elkie and Susanne','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 30','10:15am','11:45am');
INSERT INTO "Events" VALUES (2403,'Challenge 1stand up by Erik','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 30','11:45am','12:30pm');
INSERT INTO "Events" VALUES (2404,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 30','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2405,'@work powered by TI & DBWby Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 30','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2406,'Check-out by Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','MONDAY May 30','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2407,'Check-in by Tom, Elkie, Susanne,','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 30','09:45am','10:15am');
INSERT INTO "Events" VALUES (2408,'PPiby Tom, Elkie and Susanne,','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 30','10:15am','11:45am');
INSERT INTO "Events" VALUES (2409,'Challenge 2 stand up bu Tom, challenge 3 stand up by Davey, challenge 4 stand op bij Mathijs, challenge 5 stand up by Elkie, challenge 6 stand up by Susanne','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 30','11:45am','12:30pm');
INSERT INTO "Events" VALUES (2410,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 30','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2411,'@work powered by TI & DBWby Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 30','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2412,'Check-out by Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY May 30','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2413,'Challenge 2 kick-off','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY May 30','09:30am','05:00pm');
INSERT INTO "Events" VALUES (2414,'Track day 10> Personal Purpose by Lorna, Lolly and Sam. > Company Adventure by Peter and Stella. > Entrepreneur & Business by Jochem and Jeroen.','Boyan Slat (tribune)','EMBRACEAll students','TUESDAY May 31','09:30am','04:00pm');
INSERT INTO "Events" VALUES (2415,'DBW  by Sandra','Greta Thunberg (meeting space)','MASTER DTEAll students','TUESDAY May 31','11:00am','12:30pm');
INSERT INTO "Events" VALUES (2416,'PPI by Lorna','Leonardo da Vinci (experience room)','MASTER DTEAll students','TUESDAY May 31','09:00am','11:00am');
INSERT INTO "Events" VALUES (2417,'MDTE stand-up lunch','Leonardo da Vinci (experience room)','PULSERS only','TUESDAY May 31','12:00pm','01:00pm');
INSERT INTO "Events" VALUES (2418,'Group check-in (reminder ToL)','Boyan Slat (tribune)','EMBRACEAll students','WEDNESDAY June 1','09:30am','10:00am');
INSERT INTO "Events" VALUES (2419,'Pulsed for Good day for ALL Embrace TEC students:Improve the prototypesWith Gert, Zeynep, Lolly, Jop & Steffie','Boyan Slat (tribune)','EMBRACEAll students','WEDNESDAY June 1','10:00am','01:00pm');
INSERT INTO "Events" VALUES (2420,'DBWednesday timeslot: design-based working support by Zeynep, Lise and/or Steffie','Boyan Slat (tribune)','EMBRACEAll students','WEDNESDAY June 1','01:00pm','02:30pm');
INSERT INTO "Events" VALUES (2421,'Pulsed for Good day for ALL Embrace TEC students: Improve the prototypesWith Gert, Zeynep, Lolly, Jop, Stella & Steffie','Boyan Slat (tribune)','EMBRACEAll students','WEDNESDAY June 1','02:30pm','04:00pm');
INSERT INTO "Events" VALUES (2422,'Check-inby Tom and Susanne','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 1','09:45am','10:15am');
INSERT INTO "Events" VALUES (2423,'Professional identityby Tom and Susanne','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 1','10:15am','11:45am');
INSERT INTO "Events" VALUES (2424,'@work','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 1','11:45am','12:15pm');
INSERT INTO "Events" VALUES (2425,'Digital dummy time','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 1','12:15pm','12:45pm');
INSERT INTO "Events" VALUES (2426,'Lunch','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 1','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2427,'@work powered by DBWby Davey and Jop','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 1','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2428,'Check-out by Davey and Jop','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 1','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2429,'Check-in Empower + Embrace team','Greta Thunberg (meeting space)','PULSERS only','WEDNESDAY June 1','08:45am','09:15am');
INSERT INTO "Events" VALUES (2430,'Prep time Empower + Embrace team','Greta Thunberg (meeting space)','PULSERS only','WEDNESDAY June 1','09:15am','09:45am');
INSERT INTO "Events" VALUES (2431,'Check-inby Tom and Susanne','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 1','09:45am','10:15am');
INSERT INTO "Events" VALUES (2432,'Professional identityby Tom and Susanne','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 1','10:15am','11:45am');
INSERT INTO "Events" VALUES (2433,'@work','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 1','11:45am','12:15pm');
INSERT INTO "Events" VALUES (2434,'Digital dummy time','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 1','12:15pm','12:45pm');
INSERT INTO "Events" VALUES (2435,'Lunch','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 1','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2436,'@work powered by DBWby Davey and Jop','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 1','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2437,'Check-out by Davey and Jop','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 1','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2438,'Group coaching','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY June 2','09:00am','11:00am');
INSERT INTO "Events" VALUES (2439,'Group check-in','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY June 2','11:00am','11:30am');
INSERT INTO "Events" VALUES (2440,'Pulsed for Good day for ALL Embrace TEC students: Build-up for Showmoment','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY June 2','11:30am','12:30pm');
INSERT INTO "Events" VALUES (2441,'Pulsed for Good day for ALL Embrace TEC students: final Showmoment','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY June 2','01:00pm','03:30pm');
INSERT INTO "Events" VALUES (2442,'Group check-out','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY June 2','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2443,'Group coaching','John Kormeling (prototyping space)','EMBRACEAll students','THURSDAY June 2','09:00am','11:00am');
INSERT INTO "Events" VALUES (2444,'DT by Stella','Greta Thunberg (meeting space)','MASTER DTEAll students','THURSDAY June 2','09:00am','11:00am');
INSERT INTO "Events" VALUES (2445,'PBR guest lecture by Janienke Sturm','Greta Thunberg (meeting space)','MASTER DTEAll students','THURSDAY June 2','11:15am','12:15pm');
INSERT INTO "Events" VALUES (2446,'DT by Stella','Greta Thunberg (meeting space)','MASTER DTEAll students','THURSDAY June 2','01:00pm','03:00pm');
INSERT INTO "Events" VALUES (2447,'Technophilosophy by Rens','Greta Thunberg (meeting space)','MASTER DTEAll students','THURSDAY June 2','03:00pm','05:00pm');
INSERT INTO "Events" VALUES (2448,'Group coaching','Pulsers(long table)','EMBRACEAll students','THURSDAY June 2','09:00am','11:00am');
INSERT INTO "Events" VALUES (2449,'Culture shower','Pulsers(long table)','PULSERS only','THURSDAY June 2','12:00pm','01:00pm');
INSERT INTO "Events" VALUES (2450,'Group coaching','Leonardo da Vinci (experience room)','EMBRACEAll students','THURSDAY June 2','09:00am','11:00am');
INSERT INTO "Events" VALUES (2451,'Group coaching','External','EMBRACEAll students','THURSDAY June 2','09:00am','11:00am');
INSERT INTO "Events" VALUES (2452,'Check-in Empower team','Boyan Slat (tribune)','PULSERS only','FRIDAY June 3','08:30am','08:45am');
INSERT INTO "Events" VALUES (2453,'Prep time Empower team','Boyan Slat (tribune)','PULSERS only','FRIDAY June 3','09:00am','09:30am');
INSERT INTO "Events" VALUES (2454,'Check-in by Elkie','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 3','09:15am','09:30am');
INSERT INTO "Events" VALUES (2455,'PPI talentclasses by Elkie, Gert ,Tom and Thom/working time','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 3','10:00am','12:45pm');
INSERT INTO "Events" VALUES (2456,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 3','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2457,'@work powered by TI & DBWby Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 3','01:15pm','03:30pm');
INSERT INTO "Events" VALUES (2458,'Check-out by Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 3','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2459,'Check-in by Elkie','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 3','09:15am','09:30am');
INSERT INTO "Events" VALUES (2460,'PPI talentclasses by Elkie, Gert ,Tom and Thom/working time','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 3','10:00am','12:45pm');
INSERT INTO "Events" VALUES (2461,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 3','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2462,'@work powered by TI & DBWby Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 3','01:15pm','03:30pm');
INSERT INTO "Events" VALUES (2463,'Check-out by Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 3','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2464,'Seng by Jeroen','Greta Thunberg (meeting space)','MASTER DTEAll students','FRIDAY June 3','09:00am','12:30pm');
INSERT INTO "Events" VALUES (2465,'DBW by Sandra, Stella & Jeroen','Pulsers(long table)','MASTER DTEAll students','FRIDAY June 3','01:30pm','02:30pm');
INSERT INTO "Events" VALUES (2466,'Pentecost','Boyan Slat (tribune)',NULL,'MONDAY June 6','08:30am','07:16pm');
INSERT INTO "Events" VALUES (2467,'Track day 11> Personal Purpose by Lorna, Lolly and Sam. > Company Adventure by Peter and Stella. > Entrepreneur & Business by Jochem and Jeroen.','Boyan Slat (tribune)','EMBRACEAll students','TUESDAY June 7','09:30am','04:00pm');
INSERT INTO "Events" VALUES (2468,'PPI by Lorna','Greta Thunberg (meeting space)','MASTER DTEAll students','TUESDAY June 7','09:00am','11:00am');
INSERT INTO "Events" VALUES (2469,'PBR by Jeroen','Greta Thunberg (meeting space)','MASTER DTEAll students','TUESDAY June 7','01:30pm','03:30pm');
INSERT INTO "Events" VALUES (2470,'MDTE stand-up lunch','Pulsers(long table)','PULSERS only','TUESDAY June 7','12:00pm','01:00pm');
INSERT INTO "Events" VALUES (2471,'Learning Expo assessment Group 1','Leonardo da Vinci (experience room)','EMBRACEAll students','TUESDAY June 7','09:00am','10:00am');
INSERT INTO "Events" VALUES (2472,'Learning Expo assessment Group 2','Leonardo da Vinci (experience room)','EMBRACEAll students','TUESDAY June 7','10:15am','11:15am');
INSERT INTO "Events" VALUES (2473,'Learning Expo assessment Group 3','Leonardo da Vinci (experience room)','EMBRACEAll students','TUESDAY June 7','11:30am','12:30pm');
INSERT INTO "Events" VALUES (2474,'Learning Expo assessment Group 4','Leonardo da Vinci (experience room)','EMBRACEAll students','TUESDAY June 7','01:00pm','02:00pm');
INSERT INTO "Events" VALUES (2475,'Learning Expo assessment Group 5','Leonardo da Vinci (experience room)','EMBRACEAll students','TUESDAY June 7','02:15pm','03:15pm');
INSERT INTO "Events" VALUES (2476,'Learning Expo assessment Group 6','Leonardo da Vinci (experience room)','EMBRACEAll students','TUESDAY June 7','03:30pm','04:30pm');
INSERT INTO "Events" VALUES (2477,'Check-inby Tom and Susanne','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY June 8','09:45am','10:15am');
INSERT INTO "Events" VALUES (2478,'Professional identityby Tom and Susanne','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY June 8','10:15am','11:45am');
INSERT INTO "Events" VALUES (2479,'@work','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY June 8','11:45am','12:15pm');
INSERT INTO "Events" VALUES (2480,'Digital dummy time','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY June 8','12:15pm','12:45pm');
INSERT INTO "Events" VALUES (2481,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY June 8','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2482,'@work powered by DBWby Davey and Jop','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY June 8','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2483,'Check-out by Davey and Jop','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY June 8','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2484,'Check-in Empower + Embrace team','Koybe Bryant (black tables)','PULSERS only','WEDNESDAY June 8','08:45am','09:15am');
INSERT INTO "Events" VALUES (2485,'Prep time Empower + Embrace team','Koybe Bryant (black tables)','PULSERS only','WEDNESDAY June 8','09:15am','09:45am');
INSERT INTO "Events" VALUES (2486,'Check-inby Tom and Susanne','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY June 8','09:45am','10:15am');
INSERT INTO "Events" VALUES (2487,'Professional identityby Tom and Susanne','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY June 8','10:15am','11:45am');
INSERT INTO "Events" VALUES (2488,'@work','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY June 8','11:45am','12:15pm');
INSERT INTO "Events" VALUES (2489,'Digital dummy time','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY June 8','12:15pm','12:45pm');
INSERT INTO "Events" VALUES (2490,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY June 8','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2491,'@work powered by DBWby Davey and Jop','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY June 8','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2492,'Check-out by Davey and Jop','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY June 8','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2493,'Learning Expo assessment Group 7','Leonardo da Vinci (experience room)','EMBRACEAll students','WEDNESDAY June 8','09:00am','10:00am');
INSERT INTO "Events" VALUES (2494,'Learning Expo assessment Group 8','Leonardo da Vinci (experience room)','EMBRACEAll students','WEDNESDAY June 8','10:15am','11:15am');
INSERT INTO "Events" VALUES (2495,'Learning Expo assessment Group 9','Leonardo da Vinci (experience room)','EMBRACEAll students','WEDNESDAY June 8','11:30am','12:30pm');
INSERT INTO "Events" VALUES (2496,'Learning Expo assessment Group 10','Leonardo da Vinci (experience room)','EMBRACEAll students','WEDNESDAY June 8','01:00pm','02:00pm');
INSERT INTO "Events" VALUES (2497,'Learning Expo assessment Group 11','Leonardo da Vinci (experience room)','EMBRACEAll students','WEDNESDAY June 8','02:15pm','03:15pm');
INSERT INTO "Events" VALUES (2498,'Learning Expo assessment Group 12','Leonardo da Vinci (experience room)','EMBRACEAll students','WEDNESDAY June 8','03:30pm','04:30pm');
INSERT INTO "Events" VALUES (2499,'Themes of life - Pressure stress anxiety','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY June 9','09:00am','11:00am');
INSERT INTO "Events" VALUES (2500,'Themes of Life - Balancing life and focus','John Kormeling (prototyping space)','EMBRACEAll students','THURSDAY June 9','09:00am','11:00am');
INSERT INTO "Events" VALUES (2501,'Workshop by Lorna “communication and cross cultural communication + taking the lead + social skills”','John Kormeling (prototyping space)','EMBRACEAll students','THURSDAY June 9','12:30pm','03:30pm');
INSERT INTO "Events" VALUES (2502,'DBW Q&A by Sandra','Greta Thunberg (meeting space)','MASTER DTEAll students','THURSDAY June 9','01:00pm','02:00pm');
INSERT INTO "Events" VALUES (2503,'PBR by Sandra','Greta Thunberg (meeting space)','MASTER DTEAll students','THURSDAY June 9','02:00pm','03:30pm');
INSERT INTO "Events" VALUES (2504,'Themes of Life - Love yourself and others','Pulsers(long table)','EMBRACEAll students','THURSDAY June 9','09:00am','11:00am');
INSERT INTO "Events" VALUES (2505,'Learning Expo assessment Group 13','Leonardo da Vinci (experience room)','EMBRACEAll students','THURSDAY June 9','09:00am','10:00am');
INSERT INTO "Events" VALUES (2506,'Learning Expo assessment Group 14','Leonardo da Vinci (experience room)','EMBRACEAll students','THURSDAY June 9','10:15am','11:15am');
INSERT INTO "Events" VALUES (2507,'Learning Expo assessment Group 15','Leonardo da Vinci (experience room)','EMBRACEAll students','THURSDAY June 9','11:30am','12:30pm');
INSERT INTO "Events" VALUES (2508,'Learning Expo assessment Group 16','Leonardo da Vinci (experience room)','EMBRACEAll students','THURSDAY June 9','01:00pm','02:00pm');
INSERT INTO "Events" VALUES (2509,'Learning Expo assessment Group 17','Leonardo da Vinci (experience room)','EMBRACEAll students','THURSDAY June 9','02:15pm','03:15pm');
INSERT INTO "Events" VALUES (2510,'Learning Expo assessment Group 18','Leonardo da Vinci (experience room)','EMBRACEAll students','THURSDAY June 9','03:30pm','05:00pm');
INSERT INTO "Events" VALUES (2511,'EDEX Leadership expedition & Student booster day 1/2 by Jochem, Erik, Peter, Gert and Elkie?','External','PULSERS only','THURSDAY June 9','08:30am','07:16pm');
INSERT INTO "Events" VALUES (2512,'Themes of Life - Planning and procrastination','Online (add link or Groow course code)','EMBRACEAll students','THURSDAY June 9','09:00am','11:00am');
INSERT INTO "Events" VALUES (2513,'Themes of Life - Brainnovation and Curiosity',NULL,'EMBRACEAll students','THURSDAY June 9','09:00am','11:00am');
INSERT INTO "Events" VALUES (2514,'Check-in Empower team','Boyan Slat (tribune)','PULSERS only','FRIDAY June 10','08:30am','08:45am');
INSERT INTO "Events" VALUES (2515,'Prep time Empower team','Boyan Slat (tribune)','PULSERS only','FRIDAY June 10','09:00am','09:30am');
INSERT INTO "Events" VALUES (2516,'Check-in by Elkie','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 10','09:30am','10:00am');
INSERT INTO "Events" VALUES (2517,'PPI themes of life by Elkie, Gert ,Tom and Thom/working time','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 10','10:00am','12:45pm');
INSERT INTO "Events" VALUES (2518,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 10','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2519,'@work powered by TI & DBWby Davey and Mathijs','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 10','01:15pm','03:30pm');
INSERT INTO "Events" VALUES (2520,'Check-out by Davey and Mathijs','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 10','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2521,'Check-in by Elkie','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 10','09:30am','10:00am');
INSERT INTO "Events" VALUES (2522,'PPI themes of life by Elkie, Gert , Tom and Thom/working time','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 10','10:00am','12:45pm');
INSERT INTO "Events" VALUES (2523,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 10','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2524,'@work powered by TI & DBWby Davey and Mathijs','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 10','01:15pm','03:30pm');
INSERT INTO "Events" VALUES (2525,'Check-out by Davey and Mathijs','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 10','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2526,'DT by Stella','Greta Thunberg (meeting space)','MASTER DTEAll students','FRIDAY June 10','09:00am','12:00pm');
INSERT INTO "Events" VALUES (2527,'Show & grow','Greta Thunberg (meeting space)','PULSERS only','FRIDAY June 10','12:15pm','01:15pm');
INSERT INTO "Events" VALUES (2528,'EDEX Leadership expedition & Student booster day 2/2 by Jochem, Erik, Peter, Gert and Elkie?','External','PULSERS only','FRIDAY June 10','08:30am','07:16pm');
INSERT INTO "Events" VALUES (2529,'Check-in Empower team','Boyan Slat (tribune)','PULSERS only','MONDAY June 13','08:45am','09:15am');
INSERT INTO "Events" VALUES (2530,'Prep time Empower team','Boyan Slat (tribune)','PULSERS only','MONDAY June 13','09:15am','09:45am');
INSERT INTO "Events" VALUES (2531,'Check-in by Tom, Elkie, Susanne,','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 13','09:45am','10:15am');
INSERT INTO "Events" VALUES (2532,'PPIby Tom, Elkie and Susanne','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 13','10:15am','11:45am');
INSERT INTO "Events" VALUES (2533,'Challenge 1stand up by Erik','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 13','11:45am','12:30pm');
INSERT INTO "Events" VALUES (2534,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 13','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2535,'@work powered by TI & DBWby Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 13','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2536,'Check-out by Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 13','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2537,'Check-in by Tom, Elkie, Susanne,','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 13','09:45am','10:15am');
INSERT INTO "Events" VALUES (2538,'PPiby Tom, Elkie and Susanne,','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 13','10:15am','11:45am');
INSERT INTO "Events" VALUES (2539,'Challenge 2 stand up bu Tom, challenge 3 stand up by Davey, challenge 4 stand op bij Mathijs, challenge 5 stand up by Elkie, challenge 6 stand up by Susanne','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 13','11:45am','12:30pm');
INSERT INTO "Events" VALUES (2540,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 13','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2541,'@work powered by TI & DBWby Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 13','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2542,'Check-out by Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 13','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2543,'DT by Stella','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY June 13','11:30am','01:00pm');
INSERT INTO "Events" VALUES (2544,'Seng by Jeroen & Marc','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY June 13','01:00pm','03:00pm');
INSERT INTO "Events" VALUES (2545,'DBW by Sandra','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY June 13','03:15pm','05:00pm');
INSERT INTO "Events" VALUES (2546,'Track day 12> Personal Purpose by Lorna, Lolly and Sam. > Company Adventure by Peter and Stella. > Entrepreneur & Business by Jochem and Jeroen.','Boyan Slat (tribune)','EMBRACEAll students','TUESDAY June 14','09:30am','04:00pm');
INSERT INTO "Events" VALUES (2547,'PBR by Sandra','Greta Thunberg (meeting space)','MASTER DTEAll students','TUESDAY June 14','01:00pm','03:00pm');
INSERT INTO "Events" VALUES (2548,'PPI by Lorna','Leonardo da Vinci (experience room)','MASTER DTEAll students','TUESDAY June 14','09:00am','11:00am');
INSERT INTO "Events" VALUES (2549,'MDTE stand-up lunch','Leonardo da Vinci (experience room)','PULSERS only','TUESDAY June 14','12:00pm','01:00pm');
INSERT INTO "Events" VALUES (2550,'Time to Wonder week 1 out of 2','Boyan Slat (tribune)','EMBRACEAll students','WEDNESDAY June 15','09:30am','04:15pm');
INSERT INTO "Events" VALUES (2551,'Check-inby Tom and Susanne','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 15','09:45am','10:15am');
INSERT INTO "Events" VALUES (2552,'Professional identityby Tom and Susanne','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 15','10:15am','11:45am');
INSERT INTO "Events" VALUES (2553,'@work','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 15','11:45am','12:15pm');
INSERT INTO "Events" VALUES (2554,'Digital dummy time','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 15','12:15pm','12:45pm');
INSERT INTO "Events" VALUES (2555,'Lunch','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 15','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2556,'@work powered by DBWby Davey and Jop','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 15','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2557,'Check-out by Davey and Jop','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 15','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2558,'Check-in Empower + Embrace team','Greta Thunberg (meeting space)','PULSERS only','WEDNESDAY June 15','08:45am','09:15am');
INSERT INTO "Events" VALUES (2559,'Prep time Empower + Embrace team','Greta Thunberg (meeting space)','PULSERS only','WEDNESDAY June 15','09:15am','09:45am');
INSERT INTO "Events" VALUES (2560,'Check-inby Tom and Susanne','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 15','09:45am','10:15am');
INSERT INTO "Events" VALUES (2561,'Professional identityby Tom and Susanne','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 15','10:15am','11:45am');
INSERT INTO "Events" VALUES (2562,'@work','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 15','11:45am','12:15pm');
INSERT INTO "Events" VALUES (2563,'Digital dummy time','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 15','12:15pm','12:45pm');
INSERT INTO "Events" VALUES (2564,'Lunch','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 15','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2565,'@work powered by DBWby Davey and Jop','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 15','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2566,'Check-out by Davey and Jop','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 15','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2567,'DT by Stella','External','MASTER DTEAll students','WEDNESDAY June 15','01:00pm','04:00pm');
INSERT INTO "Events" VALUES (2568,'Group coaching -> Uniqueness Story HAND-IN','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY June 16','09:00am','11:00am');
INSERT INTO "Events" VALUES (2569,'Time to Wonder week 1 out of 2','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY June 16','11:00am','04:15pm');
INSERT INTO "Events" VALUES (2570,'Group coaching -> Uniqueness Story HAND-IN','John Kormeling (prototyping space)','EMBRACEAll students','THURSDAY June 16','09:00am','11:00am');
INSERT INTO "Events" VALUES (2571,'DT by Stella','Greta Thunberg (meeting space)','MASTER DTEAll students','THURSDAY June 16','09:00am','12:00pm');
INSERT INTO "Events" VALUES (2572,'Technophilosophy by Rens','Greta Thunberg (meeting space)','MASTER DTEAll students','THURSDAY June 16','03:00pm','05:00pm');
INSERT INTO "Events" VALUES (2573,'Group coaching -> Uniqueness Story HAND-IN','Pulsers(long table)','EMBRACEAll students','THURSDAY June 16','09:00am','11:00am');
INSERT INTO "Events" VALUES (2574,'DBW by Sandra, Stella & Jeroen','Pulsers(long table)','MASTER DTEAll students','THURSDAY June 16','01:00pm','02:00pm');
INSERT INTO "Events" VALUES (2575,'Embrace TEC team meeting > Pulsed for Good team','Pulsers(long table)','PULSERS only','THURSDAY June 16','03:45pm','04:45pm');
INSERT INTO "Events" VALUES (2576,'Group coaching -> Uniqueness Story HAND-IN','Leonardo da Vinci (experience room)','EMBRACEAll students','THURSDAY June 16','09:00am','11:00am');
INSERT INTO "Events" VALUES (2577,'Check-in Empower team','Boyan Slat (tribune)','PULSERS only','FRIDAY June 17','08:30am','08:45am');
INSERT INTO "Events" VALUES (2578,'Prep time Empower team','Boyan Slat (tribune)','PULSERS only','FRIDAY June 17','09:00am','09:30am');
INSERT INTO "Events" VALUES (2579,'Check-in by Elkie','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 17','09:15am','09:30am');
INSERT INTO "Events" VALUES (2580,'Showmoments by all coaches','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 17','10:00am','12:45pm');
INSERT INTO "Events" VALUES (2581,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 17','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2582,'@work powered by TI & DBWby Davey and Mathijs','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 17','01:15pm','03:30pm');
INSERT INTO "Events" VALUES (2583,'Check-out by Davey and Mathijs','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 17','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2584,'Check-in by Elkie','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 17','09:15am','09:30am');
INSERT INTO "Events" VALUES (2585,'Showmoments by all coaches','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 17','10:00am','12:45pm');
INSERT INTO "Events" VALUES (2586,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 17','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2587,'@work powered by TI & DBWby Davey and Mathijs','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 17','01:15pm','03:30pm');
INSERT INTO "Events" VALUES (2588,'Check-out by Davey and Mathijs','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 17','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2589,'Check-in Empower team','Boyan Slat (tribune)','PULSERS only','MONDAY June 20','08:45am','09:15am');
INSERT INTO "Events" VALUES (2590,'Prep time Empower team','Boyan Slat (tribune)','PULSERS only','MONDAY June 20','09:15am','09:45am');
INSERT INTO "Events" VALUES (2591,'Check-in by Tom, Elkie, Susanne,','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 20','09:45am','10:15am');
INSERT INTO "Events" VALUES (2592,'PPIby Tom, Elkie and Susanne','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 20','10:15am','11:45am');
INSERT INTO "Events" VALUES (2593,'Challenge 1stand up by Erik','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 20','11:45am','12:30pm');
INSERT INTO "Events" VALUES (2594,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 20','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2595,'@work powered by TI & DBWby Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 20','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2596,'Check-out by Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 20','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2597,'Check-in by Tom, Elkie, Susanne,','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 20','09:45am','10:15am');
INSERT INTO "Events" VALUES (2598,'PPiby Tom, Elkie and Susanne,','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 20','10:15am','11:45am');
INSERT INTO "Events" VALUES (2599,'Challenge 2 stand up bu Tom, challenge 3 stand up by Davey, challenge 4 stand op bij Mathijs, challenge 5 stand up by Elkie, challenge 6 stand up by Susanne','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 20','11:45am','12:30pm');
INSERT INTO "Events" VALUES (2600,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 20','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2601,'@work powered by TI & DBWby Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 20','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2602,'Check-out by Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 20','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2603,'DT by Stella','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY June 20','09:00am','12:00pm');
INSERT INTO "Events" VALUES (2604,'DBW by Sandra','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY June 20','01:00pm','03:00pm');
INSERT INTO "Events" VALUES (2605,'PBR Q&A by Sandra','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY June 20','03:30pm','04:30pm');
INSERT INTO "Events" VALUES (2606,'Track day 13 > Final assessment> Personal Purpose by Lorna, Lolly and Sam. > Company Adventure by Peter and Stella. > Entrepreneur & Business by Jochem and Jeroen.','Boyan Slat (tribune)','EMBRACEAll students','TUESDAY June 21','08:30am','07:16pm');
INSERT INTO "Events" VALUES (2607,'Show & grow moment','Greta Thunberg (meeting space)','MASTER DTEAll students','TUESDAY June 21','03:00pm','05:00pm');
INSERT INTO "Events" VALUES (2608,'PPI by Lorna','Leonardo da Vinci (experience room)','MASTER DTEAll students','TUESDAY June 21','09:00am','11:00am');
INSERT INTO "Events" VALUES (2609,'MDTE stand-up lunch','Leonardo da Vinci (experience room)','PULSERS only','TUESDAY June 21','12:00pm','01:00pm');
INSERT INTO "Events" VALUES (2610,'Time to wonder week 2 of 2','Boyan Slat (tribune)','EMBRACEAll students','WEDNESDAY June 22','09:30am','04:15pm');
INSERT INTO "Events" VALUES (2611,'Check-inby Tom and Susanne','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 22','09:45am','10:15am');
INSERT INTO "Events" VALUES (2612,'Professional identityby Tom and Susanne','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 22','10:15am','11:45am');
INSERT INTO "Events" VALUES (2613,'@work','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 22','11:45am','12:15pm');
INSERT INTO "Events" VALUES (2614,'Digital dummy time','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 22','12:15pm','12:45pm');
INSERT INTO "Events" VALUES (2615,'Lunch','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 22','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2616,'@work powered by DBWby Davey and Jop','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 22','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2617,'Check-out by Davey and Jop','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 22','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2618,'Check-in Empower + Embrace team','Greta Thunberg (meeting space)','PULSERS only','WEDNESDAY June 22','08:45am','09:15am');
INSERT INTO "Events" VALUES (2619,'Prep time Empower + Embrace team','Greta Thunberg (meeting space)','PULSERS only','WEDNESDAY June 22','09:15am','09:45am');
INSERT INTO "Events" VALUES (2620,'Check-inby Tom and Susanne','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 22','09:45am','10:15am');
INSERT INTO "Events" VALUES (2621,'Professional identityby Tom and Susanne','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 22','10:15am','11:45am');
INSERT INTO "Events" VALUES (2622,'@work','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 22','11:45am','12:15pm');
INSERT INTO "Events" VALUES (2623,'Digital dummy time','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 22','12:15pm','12:45pm');
INSERT INTO "Events" VALUES (2624,'Lunch','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 22','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2625,'@work powered by DBWby Davey and Jop','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 22','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2626,'Check-out by Davey and Jop','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 22','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2627,'Time to wonder week 2 of 2','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY June 23','09:30am','04:15pm');
INSERT INTO "Events" VALUES (2628,'DT by Stella','Greta Thunberg (meeting space)','MASTER DTEAll students','THURSDAY June 23','09:00am','12:00pm');
INSERT INTO "Events" VALUES (2629,'Embrace TEC team meeting > Complete team','Greta Thunberg (meeting space)','PULSERS only','THURSDAY June 23','04:00pm','05:00pm');
INSERT INTO "Events" VALUES (2630,'Culture shower','Pulsers(long table)','PULSERS only','THURSDAY June 23','12:00pm','01:00pm');
INSERT INTO "Events" VALUES (2631,'Student booster Curio 23 3n 24 Juni by ???','External','EXTERNAL parties','THURSDAY June 23','08:30am','07:16pm');
INSERT INTO "Events" VALUES (2632,'Check-in Empower team','Boyan Slat (tribune)','PULSERS only','FRIDAY June 24','08:30am','08:45am');
INSERT INTO "Events" VALUES (2633,'Prep time Empower team','Boyan Slat (tribune)','PULSERS only','FRIDAY June 24','09:00am','09:30am');
INSERT INTO "Events" VALUES (2634,'Check-in by Elkie','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 24','09:15am','09:30am');
INSERT INTO "Events" VALUES (2635,'PPI talentclasses by Elkie, Gert ,Tom and Thom/working time','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 24','10:00am','12:45pm');
INSERT INTO "Events" VALUES (2636,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 24','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2637,'@work powered by TI & DBWby Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 24','01:15pm','03:30pm');
INSERT INTO "Events" VALUES (2638,'Check-out by Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY June 24','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2639,'Check-in by Elkie','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 24','09:15am','09:30am');
INSERT INTO "Events" VALUES (2640,'PPI talentclasses by Elkie, Gert ,Tom and Thom/working time','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 24','10:00am','12:45pm');
INSERT INTO "Events" VALUES (2641,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 24','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2642,'@work powered by TI & DBWby Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 24','01:15pm','03:30pm');
INSERT INTO "Events" VALUES (2643,'Check-out by Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY June 24','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2644,'Student booster Curio 23 3n 24 Juni by ???','External','EXTERNAL parties','FRIDAY June 24','08:30am','07:16pm');
INSERT INTO "Events" VALUES (2645,'Check-in Empower team','Boyan Slat (tribune)','PULSERS only','MONDAY June 27','08:45am','09:15am');
INSERT INTO "Events" VALUES (2646,'Prep time Empower team','Boyan Slat (tribune)','PULSERS only','MONDAY June 27','09:15am','09:45am');
INSERT INTO "Events" VALUES (2647,'Check-in by Tom, Elkie, Susanne,','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 27','09:45am','10:15am');
INSERT INTO "Events" VALUES (2648,'PPIby Tom, Elkie and Susanne','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 27','10:15am','11:45am');
INSERT INTO "Events" VALUES (2649,'Challenge 1stand up by Erik','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 27','11:45am','12:30pm');
INSERT INTO "Events" VALUES (2650,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 27','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2651,'@work powered by TI & DBWby Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 27','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2652,'Check-out by Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','MONDAY June 27','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2653,'Check-in by Tom, Elkie, Susanne,','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 27','09:45am','10:15am');
INSERT INTO "Events" VALUES (2654,'PPiby Tom, Elkie and Susanne,','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 27','10:15am','11:45am');
INSERT INTO "Events" VALUES (2655,'Challenge 2 stand up bu Tom, challenge 3 stand up by Davey, challenge 4 stand op bij Mathijs, challenge 5 stand up by Elkie, challenge 6 stand up by Susanne','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 27','11:45am','12:30pm');
INSERT INTO "Events" VALUES (2656,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 27','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2657,'@work powered by TI & DBWby Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 27','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2658,'Check-out by Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY June 27','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2659,'DT by guest lecture','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY June 27','09:00am','12:00pm');
INSERT INTO "Events" VALUES (2660,'Seng by Marc','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY June 27','01:00pm','03:00pm');
INSERT INTO "Events" VALUES (2661,'DBW by Sandra','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY June 27','03:15pm','05:00pm');
INSERT INTO "Events" VALUES (2662,'Assessments ETEC retake indicator B and/or C','Koybe Bryant (black tables)','EMBRACEAll students','TUESDAY June 28','08:30am','05:00pm');
INSERT INTO "Events" VALUES (2663,'PBR by Sandra','Greta Thunberg (meeting space)','MASTER DTEAll students','TUESDAY June 28','01:00pm','03:00pm');
INSERT INTO "Events" VALUES (2664,'PPI by Lorna','Leonardo da Vinci (experience room)','MASTER DTEAll students','TUESDAY June 28','09:00am','11:00am');
INSERT INTO "Events" VALUES (2665,'MDTE stand-up lunch','Leonardo da Vinci (experience room)','PULSERS only','TUESDAY June 28','12:00pm','01:00pm');
INSERT INTO "Events" VALUES (2666,'Board of Examiners','Leonardo da Vinci (experience room)','PULSERS only','TUESDAY June 28','04:00pm','05:00pm');
INSERT INTO "Events" VALUES (2667,'Embrace: program to be determined later','Boyan Slat (tribune)','EMBRACEAll students','WEDNESDAY June 29','09:30am','04:15pm');
INSERT INTO "Events" VALUES (2668,'Check-inby Tom and Susanne','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 29','09:45am','10:15am');
INSERT INTO "Events" VALUES (2669,'Professional identityby Tom and Susanne','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 29','10:15am','11:45am');
INSERT INTO "Events" VALUES (2670,'@work','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 29','11:45am','12:15pm');
INSERT INTO "Events" VALUES (2671,'Digital dummy time','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 29','12:15pm','12:45pm');
INSERT INTO "Events" VALUES (2672,'Lunch','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 29','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2673,'@work powered by DBWby Davey and Jop','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 29','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2674,'Check-out by Davey and Jop','John Kormeling (prototyping space)','EMPOWERAll students','WEDNESDAY June 29','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2675,'Check-in Empower team','Greta Thunberg (meeting space)','PULSERS only','WEDNESDAY June 29','08:45am','09:15am');
INSERT INTO "Events" VALUES (2676,'Prep time Empower team','Greta Thunberg (meeting space)','PULSERS only','WEDNESDAY June 29','09:15am','09:45am');
INSERT INTO "Events" VALUES (2677,'Check-inby Tom and Susanne','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 29','09:45am','10:15am');
INSERT INTO "Events" VALUES (2678,'Professional identityby Tom and Susanne','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 29','10:15am','11:45am');
INSERT INTO "Events" VALUES (2679,'@work','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 29','11:45am','12:15pm');
INSERT INTO "Events" VALUES (2680,'Digital dummy time','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 29','12:15pm','12:45pm');
INSERT INTO "Events" VALUES (2681,'Lunch','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 29','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2682,'@work powered by DBWby Davey and Jop','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 29','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2683,'Check-out by Davey and Jop','Greta Thunberg (meeting space)','EMPOWERAll students','WEDNESDAY June 29','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2684,'Family day with all Pulsers','External','PULSERS only','WEDNESDAY June 29','02:00pm','07:16pm');
INSERT INTO "Events" VALUES (2685,'Embrace: program to be determined later','Boyan Slat (tribune)','EMBRACEAll students','THURSDAY June 30','09:30am','04:15pm');
INSERT INTO "Events" VALUES (2686,'Technophilosophy by Rens','Greta Thunberg (meeting space)','MASTER DTEAll students','THURSDAY June 30','03:00pm','05:00pm');
INSERT INTO "Events" VALUES (2687,'DBW by Sandra, Stella & Jeroen','Pulsers(long table)','MASTER DTEAll students','THURSDAY June 30','01:00pm','02:00pm');
INSERT INTO "Events" VALUES (2688,'Check-in Empower team','Boyan Slat (tribune)','PULSERS only','FRIDAY July 1','08:30am','08:45am');
INSERT INTO "Events" VALUES (2689,'Prep time Empower team','Boyan Slat (tribune)','PULSERS only','FRIDAY July 1','09:00am','09:30am');
INSERT INTO "Events" VALUES (2690,'Check-in by Elkie','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY July 1','09:15am','09:30am');
INSERT INTO "Events" VALUES (2691,'PPI themes of life by Elkie, Gert ,Tom and Thom/working time','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY July 1','10:00am','12:45pm');
INSERT INTO "Events" VALUES (2692,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY July 1','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2693,'@work powered by TI & DBWby Davey and Mathijs','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY July 1','01:15pm','03:30pm');
INSERT INTO "Events" VALUES (2694,'Check-out by Davey and Mathijs','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY July 1','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2695,'Check-in by Elkie','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY July 1','09:15am','09:30am');
INSERT INTO "Events" VALUES (2696,'PPI themes of life by Elkie, Gert , Tom and Thom/working time','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY July 1','10:00am','12:45pm');
INSERT INTO "Events" VALUES (2697,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY July 1','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2698,'@work powered by TI & DBWby Davey and Mathijs','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY July 1','01:15pm','03:30pm');
INSERT INTO "Events" VALUES (2699,'Check-out by Davey and Mathijs','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY July 1','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2700,'Show & grow','Pulsers(long table)','PULSERS only','FRIDAY July 1','12:15pm','01:15pm');
INSERT INTO "Events" VALUES (2701,'Check-in Empower team','Boyan Slat (tribune)','PULSERS only','MONDAY July 4','08:45am','09:15am');
INSERT INTO "Events" VALUES (2702,'Prep time Empower team','Boyan Slat (tribune)','PULSERS only','MONDAY July 4','09:15am','09:45am');
INSERT INTO "Events" VALUES (2703,'Check-in by Tom, Elkie, Susanne,','Boyan Slat (tribune)','EMPOWERAll students','MONDAY July 4','09:45am','10:15am');
INSERT INTO "Events" VALUES (2704,'PPIby Tom, Elkie and Susanne','Boyan Slat (tribune)','EMPOWERAll students','MONDAY July 4','10:15am','11:45am');
INSERT INTO "Events" VALUES (2705,'Challenge 1stand up by Erik','Boyan Slat (tribune)','EMPOWERAll students','MONDAY July 4','11:45am','12:30pm');
INSERT INTO "Events" VALUES (2706,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','MONDAY July 4','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2707,'@work powered by TI & DBWby Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','MONDAY July 4','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2708,'Check-out by Jop and Davey','Boyan Slat (tribune)','EMPOWERAll students','MONDAY July 4','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2709,'Check-in by Tom, Elkie, Susanne,','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY July 4','09:45am','10:15am');
INSERT INTO "Events" VALUES (2710,'PPiby Tom, Elkie and Susanne,','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY July 4','10:15am','11:45am');
INSERT INTO "Events" VALUES (2711,'Challenge 2 stand up bu Tom, challenge 3 stand up by Davey, challenge 4 stand op bij Mathijs, challenge 5 stand up by Elkie, challenge 6 stand up by Susanne','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY July 4','11:45am','12:30pm');
INSERT INTO "Events" VALUES (2712,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY July 4','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2713,'@work powered by TI & DBWby Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY July 4','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2714,'Check-out by Jop and Davey','Koybe Bryant (black tables)','EMPOWERAll students','MONDAY July 4','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2715,'DT by guest lecture','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY July 4','09:00am','12:00pm');
INSERT INTO "Events" VALUES (2716,'DBW by Sandra','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY July 4','01:00pm','03:00pm');
INSERT INTO "Events" VALUES (2717,'Seng by Jeroen','Greta Thunberg (meeting space)','MASTER DTEAll students','MONDAY July 4','03:15pm','05:00pm');
INSERT INTO "Events" VALUES (2718,'ALL tracks: Re-take day','Boyan Slat (tribune)','EMBRACEAll students','TUESDAY July 5','08:30am','07:16pm');
INSERT INTO "Events" VALUES (2719,'PPI by Lorna','Leonardo da Vinci (experience room)','MASTER DTEAll students','TUESDAY July 5','09:00am','11:00am');
INSERT INTO "Events" VALUES (2720,'MDTE stand-up lunch','Leonardo da Vinci (experience room)','PULSERS only','TUESDAY July 5','12:00pm','01:00pm');
INSERT INTO "Events" VALUES (2721,'PBR by Sandra','Leonardo da Vinci (experience room)','MASTER DTEAll students','TUESDAY July 5','01:00pm','02:45pm');
INSERT INTO "Events" VALUES (2722,'Check-inby Tom and Susanne','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY July 6','09:45am','10:15am');
INSERT INTO "Events" VALUES (2723,'Professional identityby Tom and Susanne','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY July 6','10:15am','11:45am');
INSERT INTO "Events" VALUES (2724,'@work','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY July 6','11:45am','12:15pm');
INSERT INTO "Events" VALUES (2725,'Digital dummy time','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY July 6','12:15pm','12:45pm');
INSERT INTO "Events" VALUES (2726,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY July 6','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2727,'@work powered by DBWby Davey and Jop','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY July 6','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2728,'Check-out by Davey and Jop','Boyan Slat (tribune)','EMPOWERAll students','WEDNESDAY July 6','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2729,'Check-in Empower team','Koybe Bryant (black tables)','PULSERS only','WEDNESDAY July 6','08:45am','09:15am');
INSERT INTO "Events" VALUES (2730,'Prep time Empower team','Koybe Bryant (black tables)','PULSERS only','WEDNESDAY July 6','09:15am','09:45am');
INSERT INTO "Events" VALUES (2731,'Check-inby Tom and Susanne','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY July 6','09:45am','10:15am');
INSERT INTO "Events" VALUES (2732,'Professional identityby Tom and Susanne','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY July 6','10:15am','11:45am');
INSERT INTO "Events" VALUES (2733,'@work','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY July 6','11:45am','12:15pm');
INSERT INTO "Events" VALUES (2734,'Digital dummy time','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY July 6','12:15pm','12:45pm');
INSERT INTO "Events" VALUES (2735,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY July 6','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2736,'@work powered by DBWby Davey and Jop','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY July 6','01:15pm','03:45pm');
INSERT INTO "Events" VALUES (2737,'Check-out by Davey and Jop','Koybe Bryant (black tables)','EMPOWERAll students','WEDNESDAY July 6','03:45pm','04:15pm');
INSERT INTO "Events" VALUES (2738,'DT by Stella','Greta Thunberg (meeting space)','MASTER DTEAll students','THURSDAY July 7','09:00am','12:00pm');
INSERT INTO "Events" VALUES (2739,'Check-in Empower team','Boyan Slat (tribune)','PULSERS only','FRIDAY July 8','08:30am','08:45am');
INSERT INTO "Events" VALUES (2740,'Prep time Empower team','Boyan Slat (tribune)','PULSERS only','FRIDAY July 8','09:00am','09:30am');
INSERT INTO "Events" VALUES (2741,'Check-in by Elkie','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY July 8','09:15am','09:30am');
INSERT INTO "Events" VALUES (2742,'Showmoments by all coaches','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY July 8','10:00am','12:45pm');
INSERT INTO "Events" VALUES (2743,'Lunch','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY July 8','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2744,'@work powered by TI & DBWby Davey and Mathijs','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY July 8','01:15pm','03:30pm');
INSERT INTO "Events" VALUES (2745,'Check-out by Davey and Mathijs','Boyan Slat (tribune)','EMPOWERAll students','FRIDAY July 8','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2746,'Check-in by Elkie','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY July 8','09:15am','09:30am');
INSERT INTO "Events" VALUES (2747,'Showmoments by all coaches','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY July 8','10:00am','12:45pm');
INSERT INTO "Events" VALUES (2748,'Lunch','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY July 8','12:45pm','01:15pm');
INSERT INTO "Events" VALUES (2749,'@work powered by TI & DBWby Davey and Mathijs','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY July 8','01:15pm','03:30pm');
INSERT INTO "Events" VALUES (2750,'Check-out by Davey and Mathijs','Koybe Bryant (black tables)','EMPOWERAll students','FRIDAY July 8','03:30pm','04:00pm');
INSERT INTO "Events" VALUES (2751,'Show & Grow moment','Greta Thunberg (meeting space)','MASTER DTEAll students','FRIDAY July 8','11:00am','12:45pm');
INSERT INTO "Events" VALUES (2752,'KLUB PULSED FESTIVAL','External','EmbraceTEC week 20: Round up','FRIDAY July 8','08:30am','07:16pm');
INSERT INTO "Events" VALUES (2753,'Pulsed clean up day!','Boyan Slat (tribune)','PULSERS only','TUESDAY July 12','08:30am','07:16pm');
INSERT INTO "Events" VALUES (2754,'Team Up','External','PULSERS only','THURSDAY July 14','08:30am','07:16pm');
INSERT INTO "Events" VALUES (2755,'Team Up','External','PULSERS only','FRIDAY July 15','08:30am','07:16pm');
COMMIT;
